### PR TITLE
Update mapping and git workflow actions

### PR DESCRIPTION
**Pull request by bloodcloak**
Add if conditional to WUT and Wiki CI Deploy Jobs to only run if on bsmg's repo and echos to note that the job was skipped due to not running on the bsmg repo.
I tested it as thoroughly as I could. It should work?

This was done so I could keep the actions running on my fork but not spam my github notifications with failed actions whenever I made a commit. Should be useful for others that forked the wiki.
___
These wiki changes were added as a test to ensure that my modifications to the workflows didn't break anything I couldn't test.

Extended Mapping:
- Modify 360/90 characteristic warning to link relevant practices pages 
- Add same warning to 360/90 section

Map Home:
- Add expired web session as cause for general beatsaver error

### CODE REVIEW

**Comment by Awagi** [comment]
By default, Github Actions are disabled in forks. Though I understand the problem here to be handling precisely which workflow can and which can not run.

To do so while avoiding being limited to this single main "beat-saber-modding-group/wiki" repository, I suggest adding trigger variables for each workflow (in Secrets for example, because it is not reproduced through forks) to enable it.

The changed conditions would be:

```yml
    if: secrets.ENABLE_CI == "1"
```
```yml
    if: secrets.ENABLE_WUT == "1"
```

In this repo, set `ENABLE_CI` and `ENABLE_WUT` to `1` in Secrets.

This would allow forks to use the Actions without changing the file, just setting up the variable in Secrets. And by default, even if Github Actions is enabled in the project settings, CI and WUT wouldn't run.

**Comment by bloodcloak** [comment]
Oh, good idea. Ill get to modifying the yaml after my classes today

**Comment by bloodcloak** [comment]
I was successful in modifying and testing the secrets implementation on my own repo. Even skips if no secrets are set and has an updated error message

Secrets are `ENABLE_WUT` and `ENABLE_CI_DEPLOY` and need to be set to a value of `1`

**Comment by bloodcloak** [comment]
I have renamed the var name to just ENABLE.

The only problem with that suggestion of another job is that the fail will then cause a fail X in the commit build which I want to silence so I can use it as an indicator on for the ci docker builds to know what I messed with didn't break anything. 

I can't seem to find any documentation where I could silently fail the job or natively pass variables between jobs that allow me to use the solutions I can come up with. I also wasn't able to get the if conditional to use the secrets at a job level. Documentation of the env context which I am using to poll the secret supports this problem in that its not supported. Only for job-step level which I have implemented https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#env-context

I have modified the workflows to be more efficient in disabling the steps to exit out quicker.
I do want to specify that the disable for Wiki CI is only for the deploy job since a fork won't need to deploy to the server but the build job would still be useful to catch failures like in pr #120

**Comment by megalon** [comment]
Ah, I see.
I believe you can have "silent" failures, by using the `if: failure()` condition.
However, if the code triggered by that conditional succeeds, then it causes the job to pass.

I originally thought something like this would work
```
  check_enabled:
    runs-on: ubuntu-latest
    env:
      ENABLE: ${{ secrets.ENABLE_CI_DEPLOY }}

    steps:
      - name: Check if enabled
        if: env.ENABLE == 1
        run: echo ENABLE_CI_DEPLOY Secret set to 1. Action will attempt to run.

      - name: Display message if disabled
        if: failure()
        run: echo ENABLE_CI_DEPLOY Secret not set to 1, action will build only, but skip deploy.

  build:
    ...

  deploy:
    needs: [check_enabled, build]
    ...

```
However, `if: failure()` seems to catch the failure condition and prevent the job from failing.
This would then allow `deploy` to run, because `check_enabled` technically "passed".

If I remove the `if: failure()` conditional, then the `check_enabled` job fails as expected, and you would end up getting an email about the job failing.

I'm going to do a bit more testing, but it looks like what you have here right now is the best way to achieve this.

**Pull request merged**
