### PR TITLE
Yeeted old stuffs

### PR DESCRIPTION
**Pull request by LDeathh**
Removed BSQI as it hasn't been updated in a while.

### CODE REVIEW

**Comment by megalon** [comment]
Does BSQI not work anymore?

**Comment by LDeathh** [comment]
The last update for it was to work on 1.6.x nearly 3 months ago, I'm not entirely sure if it works on 1.7 but regardless it uses an older BMBF that has some bugs so I thought it should probably get removed just in case. Although now that I think about it I could try to ask NyanBlade if they're still working on it.

**Comment by megalon** [comment]
Did you ask NyanBlade about this?
If not, I'm fine with merging this as is

**Comment by LDeathh** [comment]
ah sorry about the wait i forgot about this i couldnt find a way to ask him

**Comment by megalon** [comment]
Alright, fair enough.
Going to go ahead and merge then.

**Pull request merged**
