### PR TITLE
Extended Mapping launch

### PR DESCRIPTION
**Pull request by helencarnate**
Significant additions to Extended Mapping, new images, updated credits page, and added link to mapping home. All tested locally.

### CODE REVIEW

**Comment by helencarnate** [comment]
Made all requested fixes (sorry about that). Squashed commits. Thank you!

**Comment by megalon** [comment]
Oh I didn't notice that issue with the menu!
I think it'd be best to remove the degree symbol from headers for now, if that's going to happen.

**Comment by helencarnate** [comment]
One more time... this time with feeling! I reloaded Yarn and the ASCII "°" renders fine so I did a find/replace on all &deg;.

**Comment by megalon** [comment]
I guess that the sidebar generator doesn't support UTF-8 encoding.
This looks like a good solution

**Pull request merged**
