### PR TITLE
Update quest-modding.md

### PR DESCRIPTION
**Pull request by RedBrumbler**

### CODE REVIEW

**Comment by RedBrumbler** [comment]
forgot to comment, added more of my guides to this file, you could also just add my entire wiki on mod guides through this link if you think that is better: https://github.com/RedBrumbler/BMBFCustomSabers/wiki/RedBrumblers-Asset-Mod-Guide-Wiki

**Comment by megalon** [comment]
That could be helpful.
I see that your platform guide is not listed here on the BSMG wiki, but you have a page for it on your asset mod guide. Is there a reason for that?

**Comment by RedBrumbler** [comment]
Really only because it's a bit confusing as to what it actually is, because it is not the entire stage, it is just the rectangle you're standing on

**Comment by megalon** [comment]
You can add the link to the main wiki page if you want, but I'm not sure that we need it, since it then links to the other pages that are already listed.
It also looks like the wiki pages are all listed in the sidebar on the GitHub wiki in each of those links you've added as well

**Comment by RedBrumbler** [comment]
I think a better course of action would then be to add the main wiki page and just put a small paragraph beneath to show "this is where these guides live: (...)"

**Comment by megalon** [comment]
That works for me

**Comment by megalon** [comment]
I've made some changes. How does that look to you?

**Pull request closed without merging**
